{% set name = "grpc-google-iam-v1" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grpc-google-iam-v1-{{ version }}.tar.gz
  sha256: fad318608b9e093258fbf12529180f400d1c44453698a33509cc6ecf005b294e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - googleapis-common-protos-grpc >=1.56.0, <2.0.0dev
    - grpcio >=1.44.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  requires:
    - pip
  imports:
    - google.iam.v1
    - google.iam.v1.iam_policy_pb2
    - google.iam.v1.logging
    - google.iam.v1.logging.audit_data_pb2
    - google.iam.v1.policy_pb2
  commands:
    - pip check

about:
  home: https://github.com/googleapis/googleapis
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: GRPC library for the google-iam-v1 service
  description: |
    grpc-google-iam-v1 is the IDL-derived library for the
    google-iam v1 service in the googleapis repository.

  doc_url: https://github.com/googleapis/googleapis
  dev_url: https://github.com/googleapis/googleapis/tree/master/google/iam/v1

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
