{% set name = "grpc-google-iam-v1" %}
{% set version = "0.11.4" %}
{% set data = load_setup_py_data() %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5009e831dcec22f3ff00e89405249d6a838d1449a46ac8224907aa5b0e0b1aec

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --verbose

requirements:
  host:
    - python
    - pip >=18.1
    - googleapis-common-protos-grpc >=1.5.2
  run:
    - {{ pin_compatible('googleapis-common-protos-grpc') }}

test:
  imports:
    - google.api
    - google.iam
    - google.iam.v1
    - google.iam.v1.iam_policy_pb2
    - google.iam.v1.logging
    - google.iam.v1.logging.audit_data_pb2
    - google.iam.v1.policy_pb2
    - google.protobuf
    - google.rpc
    - google.rpc.code_pb2
    - google.rpc.error_details_pb2
    - google.rpc.status_pb2
    - grpc

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: APACHE
  summary: {{ data.get('description') }}

  description: |
    grpc-google-iam-v1 is the IDL-derived library for the
    google-iam (v1) service in the googleapis repository.

  doc_url: https://github.com/googleapis/googleapis
  dev_url: https://github.com/googleapis/googleapis/tree/master/google/iam/v1

extra:
  recipe-maintainers:
    - BrentDorsey
