{% set name = "grpc-google-iam-v1" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grpc-google-iam-v1-{{ version }}.tar.gz
  sha256: 3ff4b2fd9d990965e410965253c0da6f66205d5a8291c4c31c6ebecca18a9001

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - googleapis-common-protos >=1.56.0,<2.0.0dev
    - googleapis-common-protos-grpc
    - grpcio >=1.44.0,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - google.iam.v1
    - google.iam.v1.iam_policy_pb2
    - google.iam.v1.logging
    - google.iam.v1.logging.audit_data_pb2
    - google.iam.v1.policy_pb2
  commands:
    - pip check

about:
  home: https://github.com/googleapis/googleapis
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: GRPC library for the google-iam-v1 service
  description: |
    grpc-google-iam-v1 is the IDL-derived library for the
    google-iam v1 service in the googleapis repository.

  doc_url: https://github.com/googleapis/googleapis
  dev_url: https://github.com/googleapis/googleapis/tree/master/google/iam/v1

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
