schema_version: 1

context:
  name: grpc-google-iam-v1
  version: 0.14.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/grpc_google_iam_v1-${{ version }}.tar.gz
  sha256: 392b3796947ed6334e61171d9ab06bf7eb357f554e5fc7556ad7aab6d0e17038

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - grpcio >=1.44.0,<2.0.0
    - googleapis-common-protos >=1.63.2,<2.0.0
    - googleapis-common-protos-grpc
    - protobuf >=4.25.8,<8.0.0
tests:
  - python:
      imports:
        - google.iam.v1
        - google.iam.v1.iam_policy_pb2
        - google.iam.v1.logging
        - google.iam.v1.logging.audit_data_pb2
        - google.iam.v1.policy_pb2
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: GRPC library for the google-iam-v1 service
  description: |
    grpc-google-iam-v1 is the IDL-derived library for the
    google-iam v1 service in the googleapis repository.

  homepage: https://github.com/googleapis/google-cloud-python/tree/main/packages/grpc-google-iam-v1
  repository: https://github.com/googleapis/google-cloud-python/tree/main/packages/grpc-google-iam-v1
  documentation: https://github.com/googleapis/google-cloud-python/blob/main/packages/grpc-google-iam-v1/README.rst

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
